model = "SGP4"

bbox = [-90, -180, 90, 180]
interval = 1
animation = true
hosts = ["192.168.0.11:1969", "192.168.0.12:1969", "192.168.0.13:1969", "192.168.0.14:1969"]
peeringhosts = ["192.168.0.11:1970", "192.168.0.12:1970", "192.168.0.13:1970", "192.168.0.14:1970"]
database = false

[sgp4params]
starttime = 2021-05-01T12:00:00+00:00

[networkparams]
islpropagation = 3.336e-6
bandwidth = 100
mincommsaltitude = 100_000
minelevation = 30
gstpropagation = 3.336e-6
groundstationconnectiontype = "all"

[computeparams]
vcpu_count = 2
mem_size_mib = 512
ht_enabled = false
bootparams = ""
kernel = "x"
rootfs = "x"
disk_size_mib =  20_000

[[shell]]
planes = 6
sats = 11
altitude = 780
inclination = 90.0
arcofascendingnodes = 180.0
eccentricity = 0.0

[[groundstation]]
name = "Berlin"
long = 13.32392
lat = 52.516399