model = "SGP4"

bbox = [-6.8596, -11.0020, 19.7872, 22.2767]
interval = 1
animation = true
hosts = ["192.168.0.11:1969", "192.168.0.12:1969", "192.168.0.13:1969", "192.168.0.14:1969"]
peeringhosts = ["192.168.0.11:1970", "192.168.0.12:1970", "192.168.0.13:1970", "192.168.0.14:1970"]
database = false

[sgp4params]
starttime = 2021-05-01T12:00:00+00:00

[networkparams]
islpropagation = 3.336e-6
bandwidth = 10_000_000
mincommsaltitude = 80_000
minelevation = 40
gstpropagation = 3.336e-6
groundstationconnectiontype = "all"

[computeparams]
vcpu_count = 2
mem_size_mib = 512
ht_enabled = false
bootparams = ""
kernel = "x"
rootfs = "x"
disk_size_mib =  20_000

[[shell]]
planes = 36
sats = 49
altitude = 1200
inclination = 87.9
arcofascendingnodes = 360.0
eccentricity = 0.0

[[shell]]
planes = 32
sats = 72
altitude = 1200
inclination = 40.0
arcofascendingnodes = 360.0
eccentricity = 0.0

[[shell]]
planes = 32
sats = 72
altitude = 1200
inclination = 55.0
arcofascendingnodes = 360.0
eccentricity = 0.0

[[groundstation]]
name = "Rome"
lat = 41.747222
long = 12.650556
